export enum SettingActionTypes {
  SET_ACTIVE_SEARCH_ENGINE = '@@setting/SET_ACTIVE_SEARCH_ENGINE',
  SEARCH_KEYWORD_ACTION = '@@setting/SEARCH_KEYWORD_ACTION',
  SET_CUSTOM_SUBSCRIPTIONS = '@@setting/SET_CUSTOM_SUBSCRIPTIONS',
  ADD_CUSTOM_SUBSCRIPTION_REQUEST = '@@setting/ADD_CUSTOM_SUBSCRIPTION_REQUEST',
  ADD_CUSTOM_SUBSCRIPTION_SUCCESS = '@@setting/ADD_CUSTOM_SUBSCRIPTION_SUCCESS',
  ADD_CUSTOM_SUBSCRIPTION_FAILURE = '@@setting/ADD_CUSTOM_SUBSCRIPTION_FAILURE',
  REMOVE_CUSTOM_SUBSCRIPTION = '@@setting/REMOVE_CUSTOM_SUBSCRIPTION',
}
