export const subscriptions = [
  {
    name: '自定义',
    category: '其它',
    link: '',
  },
  {
    name: 'BBC',
    category: '传统媒体',
    link: '/bbc/#CHANNEL#',
    favicon: 'https://www.bbc.com/favicon.ico',
    channel: [
      ['中文', 'chinese'],
      ['World', 'world'],
      ['UK', 'uk'],
      ['Business', 'business'],
      ['Politics', 'politics'],
      ['Health', 'health'],
      ['Education & Family', 'education'],
      ['Science & Environment', 'science_and_environment'],
      ['Technology', 'technology'],
      ['Entertainment & Arts', 'entertainment_and_arts'],
    ],
  },
  {
    name: 'Solidot',
    category: '传统媒体',
    link: '/solidot/#CHANNEL#',
    favicon: 'https://www.solidot.org/favicon.ico',
    channel: [
      ['全部', 'www'],
      ['创业', 'startup'],
      ['Linux', 'linux'],
      ['科学', 'Science'],
      ['科技', 'technology'],
      ['移动', 'mobile'],
      ['苹果', 'apple'],
      ['硬件', 'hardware'],
      ['软件', 'software'],
      ['安全', 'security'],
      ['游戏', 'games'],
      ['书籍', 'books'],
      ['ask', 'ask'],
      ['idle', 'idle'],
      ['博客', 'blog'],
      ['云计算', 'cloud'],
    ],
  },
  {
    name: 'The Economist',
    category: '传统媒体',
    favicon: 'http://www.economist.com/assets/favicon.ico',
    link: '/the-economist/#CHANNEL#',
    channel: [
      ['The world this week', 'the-world-this-week'],
      ['Letters', 'letters'],
      ['Leaders', 'leaders'],
      ['Briefings', 'briefings'],
      ['Special reports', 'special-report'],
      ['Britain', 'britain'],
      ['Europe', 'europe'],
      ['United States', 'united-states'],
      ['The Americas', 'the-americas'],
      ['Middle East and Africa', 'middle-east-and-africa'],
      ['Asia', 'asia'],
      ['China', 'china'],
      ['International', 'international'],
      ['Business', 'business'],
      ['Finance and economics', 'finance-and-economics'],
      ['Science and technology', 'science-and-technology'],
      ['Books and arts', 'books-and-arts'],
      ['Obituaries', 'obituary'],
      ['Graphic detail', 'graphic-detail'],
      ['Indicators', 'economic-and-financial-indicators'],
    ],
  },
  {
    name: '第一财经',
    category: '传统媒体',
    favicon: 'https://www.yicai.com/favicon.ico',
    link: '/yicai/#CHANNEL#',
    channel: [['直播区', 'brief']],
  },
  {
    name: '界面新闻',
    category: '传统媒体',
    favicon: 'https://www.jiemian.com/favicon.ico',
    link: '/jiemian/list/#CHANNEL#',
    channel: [
      [
        '天下',
        '天下',
        [
          ['寰球政事', '35'],
          ['天下财经', '46'],
          ['世间万象', '47'],
          ['天下奇闻', '447'],
          ['环球人物', '448'],
        ],
      ],
      ['中国', '中国', [['界面早报', '280'], ['界面晚报', '426'], ['地方新闻精选', '430']]],
      ['宏观', '宏观', [['界面宏观', '20'], ['财经24小时', '428']]],
      ['文娱', '文娱', [['明星一面', '25'], ['娱乐风向', '29'], ['影视前沿', '76']]],
      [
        '体育',
        '体育',
        [['竞技场', '11'], ['体育界', '78'], ['体育速递', '110'], ['体育早晚报', '449']],
      ],
      ['商业', '2'],
      ['科技', '65'],
      ['汽车', '汽车', [['汽车经', '14']]],
    ],
  },
  {
    name: '南方周末',
    category: '传统媒体',
    favicon: 'http://www.infzm.com/favicon.ico',
    link: '/infzm/#CHANNEL#',
    channel: [
      ['推荐', '1'],
      ['新闻', '2'],
      ['观点', '3'],
      ['文化', '4'],
      ['专题', '5'],
      ['生活', '6'],
      ['人物', '7'],
      ['影像', '8'],
    ],
  },
  {
    name: '纽约时报',
    category: '传统媒体',
    favicon: 'https://cn.nytimes.com/favicon.ico',
    link: '/nytimes/#CHANNEL#',
    channel: [['中文', ''], ['中英对照', 'dual'], ['英文', 'en']],
  },
  {
    name: '澎湃新闻',
    category: '传统媒体',
    favicon: 'http://www.thepaper.cn/favicon.ico',
    link: '/thepaper/#CHANNEL#',
    channel: [
      ['精选', 'featured'],
      ['时事', 'channel/25950'],
      ['财经', 'channel/25951'],
      ['澎湃号', 'channel/36079'],
      ['思想', 'channel/25952'],
      ['生活', 'channel/25953'],
    ],
  },
  {
    name: '卫报',
    category: '传统媒体',
    favicon: 'https://www.theguardian.com/favicon.ico',
    link: '/guardian/#CHANNEL#',
    channel: [['Editorial', 'editorial'], ['China', 'china']],
  },
  {
    name: '朝日新闻中文网',
    category: '传统媒体',
    favicon: 'https://asahichinese-j.com/favicon.ico',
    link: '/asahichinese-j/#CHANNEL#',
    channel: [
      ['日本社会', 'society'],
      ['政治・经济', 'politics_economy'],
      [
        '文娱・生活',
        'cool_japan',
        [
          ['艺能', 'cool_japan/entertainment'],
          ['动漫', 'cool_japan/anime'],
          ['生活・美食', 'cool_japan/life'],
          ['时尚・文化', 'cool_japan/style_culture'],
        ],
      ],
      [
        '旅游・活动',
        'travel',
        [
          ['资讯', 'travel/news'],
          ['风景', 'travel/scenery'],
          ['体验', 'travel/topic'],
          ['交通', 'travel/move'],
        ],
      ],
      ['体育・奥运', 'sports'],
      ['商务・商品', 'business'],
      ['IT・科技', 'technology'],
    ],
  },
  {
    name: '36kr',
    category: '新媒体',
    favicon: 'http://www.36kr.com/favicon.ico',
    link: '/36kr/newsflashes',
  },
  {
    name: '9to5',
    category: '新媒体',
    link: '/9to5/#CHANNEL#',
    favicon:
      'https://i1.wp.com/9to5mac.com/wp-content/themes/9to5-2015/images/favicons/9to5mac/icon-192x192.png',
    channel: [['Mac', 'mac'], ['Google', 'google'], ['Toys', 'toys']],
  },
  {
    name: '电脑爱好者',
    category: '新媒体',
    favicon: 'http://www.cfan.com.cn/favicon.ico',
    link: '/cfan/news',
  },
  {
    name: 'cnBeta',
    category: '新媒体',
    favicon: 'https://www.cnbeta.com/favicon.ico',
    link: '/cnbeta',
  },
  {
    name: 'Engadget 瘾科技',
    category: '新媒体',
    favicon:
      'https://s.blogsmithmedia.com/www.engadget.com/assets-h045db91064c248cf4d54f147b8a59a95/images/favicon-16x16.png?h=288a0831497b5dbbde1fdb670dc8a62c',
    link: '/engadget-cn',
  },
  {
    name: 'InfoQ 中文',
    category: '新媒体',
    favicon: 'https://static001.infoq.cn/static/infoq/www/img/InfoQ-share-icon2.jpg',
    link: '/infoq/#CHANNEL#',
    channel: [
      ['推荐', 'recommend'],
      [
        '话题',
        'topic',
        [
          ['语言 & 开发', 'topic/1'],
          ['文化 & 方法', 'topic/3'],
          ['DevOps', 'topic/4'],
          ['Java', 'topic/6'],
          ['.Net', 'topic/7'],
          ['架构', 'topic/8'],
          ['敏捷', 'topic/9'],
          ['Ruby', 'topic/10'],
          ['云计算', 'topic/11'],
          ['SOA', 'topic/12'],
          ['移动', 'topic/13'],
          ['JavaScript', 'topic/14'],
          ['大数据', 'topic/15'],
          ['Android', 'topic/16'],
          ['开源', 'topic/17'],
          ['iOS', 'topic/18'],
          ['Google', 'topic/19'],
          ['微软', 'topic/20'],
          ['安全', 'topic/21'],
          ['AWS', 'topic/26'],
          ['数据库', 'topic/30'],
        ],
      ],
    ],
  },
  {
    name: 'IT 橘子',
    category: '新媒体',
    favicon: 'https://www.itjuzi.com/favicon.ico',
    link: '/itjuzi/#CHANNEL#',
    channel: [['投融资事件', 'invest'], ['并购事件', 'merge']],
  },
  {
    name: 'The Verge',
    category: '新媒体',
    favicon: 'https://cdn.vox-cdn.com/uploads/chorus_asset/file/7395367/favicon-16x16.0.png',
    link: '/verge',
  },
  {
    name: 'ZAKER',
    category: '新媒体',
    favicon: 'https://www.myzaker.com/favicon.ico',
    link: '/zaker/#CHANNEL#',
    channel: [
      ['头条新闻', 'source/12291'],
      ['热点', 'channel/660'],
      ['娱乐', 'channel/9'],
      ['汽车', 'channel/7'],
      ['体育', 'channel/8'],
      ['科技', 'channel/13'],
      ['国内', 'channel/1'],
      ['国际', 'channel/2'],
      ['军事', 'channel/3'],
      ['财经', 'channel/4'],
      ['互联网', 'channel/5'],
    ],
  },
  {
    name: '爱范儿',
    category: '新媒体',
    favicon: 'https://www.ifanr.com/favicon.ico',
    link: '/ifanr/#CHANNEL#',
    channel: [
      ['AppSolution', 'app'],
      ['玩物志', 'coolbuy'],
      ['早报', 'category-ifanrnews'],
      ['评测', 'category-review'],
      ['新锐产品', 'category-product'],
      ['行业', 'category-business'],
      ['生活', 'category-life'],
      ['董车会', 'category-intelligentcar'],
      ['小程序', 'minapp'],
      ['爱范儿视频', 'video'],
      ['人物', 'category-people'],
    ],
  },
  {
    name: '币世界',
    category: '新媒体',
    favicon: 'https://www.bishijie.com/favicon.ico',
    link: '/bishijie/kuaixun',
  },
  {
    name: '后续',
    category: '新媒体',
    favicon: 'https://assets-1256259474.cos.ap-shanghai.myqcloud.com/icon-180.jpg',
    link: '/houxu/#CHANNEL#',
    channel: [
      ['最新专栏', 'events'],
      ['最新 Live', 'lives', [['往事进展', 'lives/realtime'], ['最新添加', 'lives/new']]],
    ],
  },
  {
    name: '机核网',
    category: '新媒体',
    favicon: 'https://www.gcores.com/favicon.ico',
    link: '/gcores/#CHANNEL#',
    channel: [
      ['资讯', 'category/news'],
      ['视频', 'category/videos'],
      ['电台', 'category/radios'],
      ['文章', 'category/articles'],
    ],
  },
  {
    name: '哔哩哔哩',
    category: '社交媒体',
    favicon: 'http://space.bilibili.com/favicon.ico',
    link: '/bilibili/#CHANNEL#',
    channel: [
      ['番剧', 'bangumi/media/#番剧媒体ID#'],
      ['用户追番列表', 'user/bangumi/#用户ID#'],
      ['UP主投稿', 'user/video/#用户ID#'],
      ['UP主专栏', 'user/article/#用户ID#'],
      ['UP主动态', 'user/dynamic/#用户ID#'],
      ['UP主频道', 'user/channel/#用户ID#/#频道ID#'],
      [
        '分区视频',
        'partion',
        [
          [
            '动画',
            'donghua',
            [
              ['MAD·AMV', 'partion/24'],
              ['MMD·3D', 'partion/25'],
              ['短片·手书·配音', 'partion/47'],
              ['综合', 'partion/27'],
            ],
          ],
          [
            '番剧',
            'fanju',
            [
              ['连载动画', 'partion/33'],
              ['完结动画', 'partion/32'],
              ['资讯', 'partion/51'],
              ['官方延伸', 'partion/152'],
            ],
          ],
          [
            '国创',
            'guochuang',
            [
              ['国产动画', 'partion/153'],
              ['国产原创相关', 'partion/168'],
              ['布袋戏', 'partion/169'],
              ['资讯', 'partion/170'],
            ],
          ],
          [
            '音乐',
            'yinyue',
            [
              ['原创音乐', 'partion/28'],
              ['翻唱', 'partion/31'],
              ['VOCALOID·UTAU', 'partion/30'],
              ['演奏', 'partion/59'],
              ['三次元音乐', 'partion/29'],
              ['OP/ED/OST', 'partion/54'],
              ['音乐选集', 'partion/130'],
            ],
          ],
          [
            '舞蹈',
            'wudao',
            [['宅舞', 'partion/20'], ['三次元舞蹈', 'partion/154'], ['舞蹈教程', 'partion/156']],
          ],
          [
            '游戏',
            'youxi',
            [
              ['单机游戏', 'partion/17'],
              ['电子竞技', 'partion/171'],
              ['手机游戏', 'partion/172'],
              ['网络游戏', 'partion/65'],
              ['桌游棋牌', 'partion/173'],
              ['GMV', 'partion/121'],
              ['音游', 'partion/136'],
              ['Mugen', 'partion/19'],
            ],
          ],
          [
            '科技',
            'keji',
            [
              ['趣味科普人文', 'partion/17'],
              ['野生技术协会', 'partion/171'],
              ['演讲·公开课', 'partion/172'],
              ['星海', 'partion/65'],
              ['数码', 'partion/173'],
              ['机械', 'partion/121'],
              ['汽车', 'partion/136'],
            ],
          ],
          [
            '生活',
            'shenghuo',
            [
              ['搞笑', 'partion/138'],
              ['日常', 'partion/21'],
              ['美食圈', 'partion/76'],
              ['动物圈', 'partion/75'],
              ['手工', 'partion/161'],
              ['绘画', 'partion/162'],
              ['ASMR', 'partion/175'],
              ['运动', 'partion/163'],
              ['其他', 'partion/174'],
            ],
          ],
          [
            '鬼畜',
            'guichu',
            [
              ['鬼畜调教', 'partion/22'],
              ['音 MAD', 'partion/26'],
              ['人力 VOCALOID', 'partion/126'],
              ['教程演示', 'partion/127'],
            ],
          ],
          [
            '时尚',
            'shishang',
            [
              ['美妆', 'partion/157'],
              ['服饰', 'partion/158'],
              ['健身', 'partion/164'],
              ['资讯', 'partion/159'],
            ],
          ],
          ['广告', 'partion/166'],
          [
            '娱乐',
            'yule',
            [['综艺', 'partion/71'], ['明星', 'partion/137'], ['Korea 相关', 'partion/131']],
          ],
          [
            '影视',
            'yinshi',
            [
              ['影视杂谈', 'partion/182'],
              ['影视剪辑', 'partion/183'],
              ['短片', 'partion/85'],
              ['预告·资讯', 'partion/184'],
              ['特摄', 'partion/86'],
            ],
          ],
          [
            '纪录片',
            'jilupian',
            [
              ['全部', 'partion/177'],
              ['人文·历史', 'partion/37'],
              ['科学·探索·自然', 'partion/178'],
              ['军事', 'partion/179'],
              ['社会·美食·旅行', 'partion/180'],
            ],
          ],
          [
            '电影',
            'dianyin',
            [
              ['全部', 'partion/23'],
              ['华语电影', 'partion/146'],
              ['欧美电影', 'partion/145'],
              ['日本电影', 'partion/146'],
              ['其他国家', 'partion/83'],
            ],
          ],
          [
            '电视剧',
            'dianshiju',
            [['全部', 'partion/11'], ['国产剧', 'partion/185'], ['海外剧', 'partion/187']],
          ],
        ],
      ],
      ['视频评论', 'video/reply/#视频ID#'],
      ['视频搜索', 'vsearch/#视频名称#'],
    ],
  },
  {
    name: '什么值得买',
    category: '购物',
    favicon: 'https://www.smzdm.com/favicon.ico',
    link: '/smzdm/#CHANNEL#',
    channel: [
      ['关键词搜索', 'keyword/#关键词#'],
      [
        '排行榜',
        'rank',
        [
          [
            '好价品类榜',
            'pinlei',
            [
              ['全部', 'ranking/pinlei/11/#小时跨度#'],
              ['时尚运动', 'ranking/pinlei/12/#小时跨度#'],
              ['3C家电', 'ranking/pinlei/13/#小时跨度#'],
              ['食品家居', 'ranking/pinlei/14/#小时跨度#'],
              ['日百母婴', 'ranking/pinlei/15/#小时跨度#'],
              ['出行游玩', 'ranking/pinlei/16/#小时跨度#'],
              ['白菜价', 'ranking/pinlei/17/#小时跨度#'],
              ['凑单品', 'ranking/pinlei/22/#小时跨度#'],
            ],
          ],
          [
            '好价电商榜',
            'dianshang',
            [
              ['券活动', 'ranking/dianshang/24/#小时跨度#'],
              ['京东', 'ranking/dianshang/23/#小时跨度#'],
              ['天猫', 'ranking/dianshang/25/#小时跨度#'],
              ['亚马逊中国', 'ranking/dianshang/26/#小时跨度#'],
              ['国美在线', 'ranking/dianshang/27/#小时跨度#'],
              ['苏宁易购', 'ranking/dianshang/28/#小时跨度#'],
              ['网易', 'ranking/dianshang/29/#小时跨度#'],
              ['西集网', 'ranking/dianshang/30/#小时跨度#'],
              ['美国亚马逊', 'ranking/dianshang/31/#小时跨度#'],
              ['日本亚马逊', 'ranking/dianshang/32/#小时跨度#'],
              ['ebay', 'ranking/dianshang/33/#小时跨度#'],
            ],
          ],
          [
            '海淘 TOP 榜',
            'haitao',
            [
              ['全部', 'ranking/haitao/39/#小时跨度#'],
              ['海外直邮', 'ranking/haitao/34/#小时跨度#'],
              ['美国榜', 'ranking/haitao/35/#小时跨度#'],
              ['欧洲榜', 'ranking/haitao/36/#小时跨度#'],
              ['澳新榜', 'ranking/haitao/37/#小时跨度#'],
              ['亚洲榜', 'ranking/haitao/38/#小时跨度#'],
              ['晒物榜', 'ranking/haitao/hsw/#小时跨度#'],
            ],
          ],
          [
            '好文原创榜',
            'haowen',
            [['原创', 'haowen/yc/#小时跨度#'], ['资讯', 'haowen/zx/#小时跨度#']],
          ],
          [
            '好物排行榜',
            'haowu',
            [
              ['新晋榜', 'ranking/haowu/yhwall/#小时跨度#'],
              ['消费众测', 'ranking/haowu/zc/#小时跨度#'],
              ['新锐品牌', 'ranking/haowu/nb/#小时跨度#'],
              ['好物榜单', 'ranking/haowu/hw/#小时跨度#'],
            ],
          ],
        ],
      ],
      ['好文', 'haowen'],
    ],
  },
];
