export enum ModalActionTypes {
  SET_SHOW_SUBSCRIPTIONS_SETTING_MODAL = '@@modal/SET_SHOW_SUBSCRIPTIONS_SETTING_MODAL',
  SET_SHOW_ADD_SUBSCRIPTION_MODAL = '@@modal/SET_SHOW_ADD_SUBSCRIPTION_MODAL',
}
